[[env]]
name = "RUST_LOG"
value = "debug"

[devshell]
packages = [
   "cargo-limit",
   "rust-analyzer",
   "nodePackages.http-server",
]

[[commands]]
name = "c"
help = "alias of cargo lcheck"
command = "cargo lcheck"

[serviceGroups.rustdoc]
description = "show rust doc as a web server"
[serviceGroups.rustdoc.services.cratedocs]
command = "cargo doc && http-server $PRJ_ROOT/target/doc/ -p 7071"
[serviceGroups.rustdoc.services.stddocs]
command = "http-server $(rustc --print sysroot)/share/doc/rust/html -p 7072"
