imports = ["services/postgres"]

[services.postgres]
package = "pkgs.postgresql_16"
setupPostgresOnStartup = true

[[env]]
name = "DBNAME"
value = "ma"

[[env]]
name = "PGPORT"
value = "7700"

[[env]]
name = "SQLX_OFFLINE"
value = "true"

[[env]]
name = "DATABASE_URL"
eval = 'postgres:///$DBNAME?port=$PGPORT\&host=$PGHOST'

[[commands]]
name = "setup-db"
help = "setup postgresql and create databaes"
command = 'sqlx database setup --database-url $DATABASE_URL'


