name: devshell
on:
  push:
    branches:
      - master
      - dev
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix develop .#ci -c "cargo" "tree"
          nix develop .#ci -c "cargo" "build"
          nix develop .#ci -c "cargo" "test"
